# Generated by Django 4.2.5 on 2023-10-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='puplish_date',
        ),
    ]
